---
title: "ASHG18"
subtitle: "American Society of Human Genetics 68th Annual Meeting"
date: "`r Sys.time()`"
params:
    hashtag: "#ASHG18"
    # Times
    start_day: "2018-10-16"
    end_day: "2018-10-20"
    timezone: "America/Los_Angeles"
    # Plot theme and colours
    theme: "theme_light"
    accent: "skyblue3"
    accent2: "#B5D2E6"
    # Analysis parameters
    kcore: 30
    topics_k: 9
    bigram_filter: 15
    # Dataset fixed, set true to stop adding new tweets
    fixed: TRUE
    # Random seed
    seed: 1
---

```{r knitr, include = FALSE}
DOCNAME <- tools::file_path_sans_ext(knitr::current_input())
knitr::opts_chunk$set(
    echo           = FALSE,
    error          = FALSE,
    fig.align      = "center",
    fig.path       = paste0("figures/", DOCNAME, "/"),
    fig.width      = 10,
    fig.height     = 8,
    message        = FALSE,
    warning        = FALSE
)
```

```{r libraries, include = FALSE}
# Twitter
library("rtweet")

# Data manipulation
library("dplyr")
library("tidyr")
library("lubridate")
library("forcats")
library("purrr")
library("stringr")

# Networks
library("igraph")

# Text analysis
library("tidytext")
library("topicmodels")

# Visualisation
library("ggplot2")
library("ggrepel")
library("ggraph")
library("wordcloud")
library("viridis")

# Images
library("webshot")
library("magick")

# Presentation
library("knitr")

# File paths
library("here")
library("fs")
```

**Parameters**

```{r params}
params_table <- data.frame(Parameter = names(params), Value = unlist(params))

kable(params_table, row.names = FALSE)
```

```{r load}
data_file <- here("data", paste0(DOCNAME, ".Rds"))

if (params$fixed) {
    if (file_exists(data_file)) {
        tweets <- readRDS(data_file)
    } else {
        stop("fixed is TRUE but no data file exists", call. = FALSE)
    }
} else {
    if (file_exists(data_file)) {
        existing_tweets <- readRDS(data_file)
        message(nrow(existing_tweets), " tweets already downloaded")
        
        new_tweets <- search_tweets(params$hashtag, 10000) %>%
            mutate(collected_at = Sys.time())
        message("Found ", nrow(new_tweets), " tweets")
        
        tweets <- new_tweets %>%
            rbind(existing_tweets) %>%
            group_by(status_id) %>%
            top_n(1, collected_at) %>%
            ungroup()
        message("Dataset now contains ", nrow(tweets), " tweets")
    } else {
        tweets <- search_tweets(params$hashtag, 10000) %>%
            mutate(collected_at = Sys.time())
        message("Found ", nrow(tweets), " tweets")
    }
    saveRDS(tweets, data_file)
}

tweets <- tweets %>%
    mutate(
        date = as_date(created_at, tz = params$timezone),
        datetime = as_datetime(created_at, tz = params$timezone),
        hour = hour(datetime)
    )
```

# Introduction

An analysis of tweets from the `r params$hashtag` hashtag for the
[American Society of Human Genetics 68th Annual meeting][ASHG18], 16-20 October
2018 at the San Diego Convention Center, San Diego USA.

A total of `r nrow(tweets)` tweets from `r length(unique(tweets$screen_name))`
users were collected using the `rtweet` R package.

```{r analysis, child = "_analysis.Rmd"}
# This chunk adds the template analysis
```

# Session info {.unnumbered}

```{r session-info}
sessionInfo()
```

[ASHG18]: https://www.ashg.org/2018meeting/index.shtml "ASHG 2018"
