---
title: "GI2018"
subtitle: "Genome Informatics 2018"
date: "Last built: `r Sys.time()`"
params:
    hashtag: "#gi2018"
    # Times
    start_day: "2018-09-17"
    end_day: "2018-09-20"
    timezone: "Europe/London"
    # Plot theme and colours
    theme: "theme_light"
    accent: "skyblue3"
    accent2: "#B5D2E6"
    # Analysis parameters
    kcore: 2
    topics_k: 6
    bigram_filter: 3
    # Dataset fixed, set true to stop adding new tweets
    fixed: TRUE
    # Random seed
    seed: 1
---

```{r setup, include = FALSE}
DOCNAME <- tools::file_path_sans_ext(knitr::current_input())
source(here::here("R", "knitr-options.R"))
```

```{r libraries, include = FALSE}
source(here::here("R", "libraries.R"))
```

<p>
  <button class="btn btn-primary" data-toggle="collapse" data-target="#Parameters">
    Parameters
  </button>
</p>

<div id="Parameters" class="collapse">
```{r params}
params_table <- data.frame(Parameter = names(params), Value = unlist(params))
kable(params_table, row.names = FALSE)
```
</div>

```{r load}
cache_file <- here("data", paste0(DOCNAME, ".Rds"))
hashtags_vec <- str_split(params$hashtag, ",")[[1]]
hashtags_query <- paste(hashtags_vec, collapse = " OR ")
tweets <- clamour_load_tweets(hashtags_query, cache_file,
                              timezone = params$timezone, fixed = params$fixed)
```

# Introduction {.unnumbered}

An analysis of tweets from the `r params$hashtag` hashtag for the
[Genome Informatics conference][GI2018], 17-20 September 2018, at the Wellcome
Genome Campus, Hinxton UK.

A total of `r nrow(tweets)` tweets from `r length(unique(tweets$screen_name))`
users were collected using the `rtweet` R package.

```{r analysis, child = "_analysis.Rmd"}
# This chunk adds the template analysis
```

# Session info {.unnumbered}

<p>
  <button class="btn btn-primary" data-toggle="collapse" data-target="#SessionInfo">
    Session info
  </button>
</p>

<div id="SessionInfo" class="collapse">  
```{r session-info}
sessioninfo::session_info()
```
</div>

[GI2018]: https://coursesandconferences.wellcomegenomecampus.org/our-events/genome-informatics-2018/ "Genome Informatics 2018"
